const mininiInfo = {
    "conini": {
      "description": "A planning addict who’s always hosting something; powered by unstoppable positivity",
      "traits": [
        "📅 🎀 🎉",
        "#hyperplanner #goodvibesonly",
        "If there’s no plan, I’ll make one!"
      ],
      "hobby": "Planning flawless events, corporate life, and keeping things✨just right✨",
      "bestie": "chonini",
      "hates": "When no one sticks to the plan. Or worse… when there is no plan. (corporate life – sometimes*)",
      "img": "img/conini-fit.png",
      "chart": "img/conini_poster.png",
      "web": "img/all_poster.png", 
      "recommend1": "img/conini_plush.png", 
      "recommend1Desc": "conini mini minini Field Day Plush Keyring",
      "recommend2": "img/conini_pen.png", 
      "recommend2Desc": "conini minini Plush Pen",
      "recommend3": "img/conini_pouch.png",
      "recommend3Desc": "conini minini Sticker Set Pouch",
      "recommend4": "img/conini_keyring.png",
      "recommend4Desc": "conini minini Beads Strap Keyring",
      "recommend5": "img/conini_pad.png",
      "recommend5Desc": "conini Memo Notepad",
      "recommend6": "img/conini_blanket.png", 
      "recommend6Desc": "conini minini Blanket"
    },
    "bnini": {
      "description": "The reliable friend who laughs along with the jokes but always steps in when something goes wrong.",
      "traits": [
        "📘 ☕ 🔁",
        "#reliablebuddy #problemsolver",
        "I’ve got your back, always."
      ],
      "hobby": "Helping out quietly, organizing things, and cooking – trying out new recipes!",
      "bestie": "selini, lenini",
      "hates": "Anything that harms its friends, being mean, ignoring problems.",
      "img": "img/bniini-fit.png",
      "chart": "img/bniini_poster.png",
      "web": "img/all_poster.png",
      "recommend1": "img/bniini_blanket.png", 
      "recommend1Desc": "bnini minini Blanket",
      "recommend2": "img/bniini_keyring.png",
      "recommend2Desc": "bnini Ice Cream Keyring",
      "recommend3": "img/bniini_umbrella.png", 
      "recommend3Desc": "bnini minini Field Day 3-Tier Umbrella",
      "recommend4": "img/bniini_passport.png", 
      "recommend4Desc": "bnini Ice Cream Passport Cover",
      "recommend5": "img/bniini_handtowel.png", 
      "recommend5Desc": "bnini Fuzzy Hand Towel",
      "recommend6": "img/bniini_pen.png", 
      "recommend6Desc": "bnini minini Plush Pen"
    },
    "lenini": {
      "description": "A mellow little peacekeeper; keeps things cozy, cherishes friends deeply, and somehow makes the world feel just a bit softer.",
      "traits": [
        "🌱 💌 ☁️",
        "#softheart #spreadingjoy",
        "I bring peace in my own quiet way!"
      ],
      "hobby": "Daydreaming, keeping three things in their bag, and quietly spreading good vibes! (lowkey phone addict*)",
      "bestie": "jenini",
      "hates": "Conflict, loud energy, and emotional tension; anything that disrupts the harmony of the group.",
      "img": "img/lenini-fit.png",
      "chart": "img/lenini_poster.png",
      "web": "img/all_poster.png", 
      "recommend1": "img/lenini_humidifier.png", 
      "recommend1Desc": "lenini minini Humidifier",
      "recommend2": "img/lenini_slippers.png", 
      "recommend2Desc": "lenini minini Plush House Slippers",
      "recommend3": "img/lenini_keyring.png", 
      "recommend3Desc": "lenini mini minini Field Day Plush Keyring",
      "recommend4": "img/lenini_charge.png", 
      "recommend4Desc": "lenini minini Wireless Charging Station",
      "recommend5": "img/lenini_pants.png", 
      "recommend5Desc": "lenini minini Fleece Pajama Pants",
      "recommend6": "img/lenini_icecream.png", 
      "recommend6Desc": "minini lenini Ice Cream Keyring"
    },
    "jenini": {
      "description": "A minini that tans like a toast, grooms like a queen, and throws the occasional cat punch.",
      "traits": [
        "🐾 🍞 ✨",
        "#catitude #purrfection #pokerface",
        "I lounge, I groom, I rule."
      ],
      "hobby": "Baking loaf, grooming, and getting into boxes",
      "bestie": "lenini",
      "hates": "being touched without permission, or crumbs on its favorite spot.",
      "img": "img/jenini-fit.png",
      "chart": "img/jenini_poster.png",
      "web": "img/all_poster.png", 
      "recommend1": "img/jenini_doll.png", 
      "recommend1Desc": "jenini mini minini Adventure Mini Doll Keyring",
      "recommend2": "img/jenini_zipper.png", 
      "recommend2Desc": "jenini minini mini Zipper Pouch",
      "recommend3": "img/jenini_pencilcase.png", 
      "recommend3Desc": "jenini minini School Bunny Plush Pencil Case",
      "recommend4": "img/jenini_pouch.png", 
      "recommend4Desc": "jenini minini Sticker Set Pouch",
      "recommend5": "img/jenini_pen.png", 
      "recommend5Desc": "jenini minini Plush Pen",
      "recommend6": "img/jenini_keyring.png", 
      "recommend6Desc": "jenini minini Beads Strap Keyring"
    },
    "chonini": {
      "description": "Clothes always spotless, vibes always on point; nothing they love more than being with their friends.",
      "traits": [
        "🎀 📸 💄",
        "#maincharacter #trendsetter",
        "I’m not extra. I’m just everything"
      ],
      "hobby": "Collecting ribbons, checking itself on mirror, and curating the cutest looks.",
      "bestie": "conini",
      "hates": "When someone steals its spotlight… or clashes with its aesthetic!",
      "img": "img/chonini-fit.png",
      "chart": "img/chonini_poster.png",
      "web": "img/all_poster.png", 
      "recommend1": "img/chonini_doll.png", 
      "recommend1Desc": "chonini Bakery Standing Doll",
      "recommend2": "img/chonini_keyring.png", 
      "recommend2Desc": "chonini Figure Keyring",
      "recommend3": "img/chonini_cushion.png", 
      "recommend3Desc": "minini chonini Face Cushion Ver. 2",
      "recommend4": "img/chonini_summer.png", 
      "recommend4Desc": "chonini Summer Standing Doll",
      "recommend5": "img/chonini_magnet.png", 
      "recommend5Desc": "chonini minini Plush Magnet",
    },
    "selini": {
      "description": "A food-loving little ball of chaos; does whatever they want and isn’t the best at reading the room. But somehow, you just can’t dislike it.",
      "traits": [
        "🌙 🔍 😴",
        "#myway #foodie",
        "I move when I’m moved… sometimes."
      ],
      "hobby": "Sleeping in, snacking, and pranking friends!",
      "bestie": "Bniini",
      "hates": "Quiet tension, awkward vibes… and anything that resembles a diet.",
      "img": "img/selini-fit.png",
      "chart": "img/selini_poster.png",
      "web": "img/all_poster.png", 
      "recommend1": "img/selini_pen.png", 
      "recommend1Desc": "selini Under The Pool Figurine Gel Pen",
      "recommend2": "img/selini_magnet.png", 
      "recommend2Desc": "selini minini Plush Magnet",
      "recommend3": "img/selini_sticky.png", 
      "recommend3Desc": "minini selini Sticky Notes",
      "recommend4": "img/selini_mug.png", 
      "recommend4Desc": "selini minini Mug",
      "recommend5": "img/selini_pouch.png", 
      "recommend5Desc": "selini minini Bag Charm Pouch",
      "recommend6": "img/selini_passport.png", 
      "recommend6Desc": "selini Ice Cream Passport Cover"
    }        
}