const resultMap = {
    'AABB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBBD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDBC': { name: "Lenini", img: "img/lenini-fit.png" },
    'ABBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBCB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDDB': { name: "Lenini", img: "img/lenini-fit.png" },
    'ACBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBDA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDCA': { name: "Lenini", img: "img/lenini-fit.png" },
    'ADBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBDB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDCB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BAAB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBDC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDCC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BAAC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBDD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDDA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BAAD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCAB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDDB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BABA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCAD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDDC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BABB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCBA': { name: "Lenini", img: "img/lenini-fit.png" },
    'CABB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BABC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'CBBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BABD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCBC': { name: "Lenini", img: "img/lenini-fit.png" },
    'CDBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BACA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCBD': { name: "Lenini", img: "img/lenini-fit.png" },
    'DABB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BACB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCCA': { name: "Lenini", img: "img/lenini-fit.png" },
    'DBBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BACC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCCB': { name: "Lenini", img: "img/lenini-fit.png" },
    'DCBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BACD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCCD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BADB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCDA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBAB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCDB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBAC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BCDD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBAD': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDAB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBBA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDAC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBBB': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDBA': { name: "Lenini", img: "img/lenini-fit.png" },
    'BBBC': { name: "Lenini", img: "img/lenini-fit.png" },
    'BDBB': { name: "Lenini", img: "img/lenini-fit.png" },          
    "ACBC": { name: "Selini", img: "img/selini-fit.png" },
    "CBBD": { name: "Selini", img: "img/selini-fit.png" },
    "CDAB": { name: "Selini", img: "img/selini-fit.png" },
    "ACCC": { name: "Selini", img: "img/selini-fit.png" },
    "CBCC": { name: "Selini", img: "img/selini-fit.png" },
    "CDAC": { name: "Selini", img: "img/selini-fit.png" },
    "ACDC": { name: "Selini", img: "img/selini-fit.png" },
    "CBDA": { name: "Selini", img: "img/selini-fit.png" },
    "CDBA": { name: "Selini", img: "img/selini-fit.png" },
    "BCAC": { name: "Selini", img: "img/selini-fit.png" },
    "CBDB": { name: "Selini", img: "img/selini-fit.png" },
    "CDBC": { name: "Selini", img: "img/selini-fit.png" },
    "BCCC": { name: "Selini", img: "img/selini-fit.png" },
    "CBDC": { name: "Selini", img: "img/selini-fit.png" },
    "CDCA": { name: "Selini", img: "img/selini-fit.png" },
    "BCDC": { name: "Selini", img: "img/selini-fit.png" },
    "CBDD": { name: "Selini", img: "img/selini-fit.png" },
    "CDCB": { name: "Selini", img: "img/selini-fit.png" },
    "CAAB": { name: "Selini", img: "img/selini-fit.png" },
    "CCAA": { name: "Selini", img: "img/selini-fit.png" },
    "CDCC": { name: "Selini", img: "img/selini-fit.png" },
    "CAAC": { name: "Selini", img: "img/selini-fit.png" },
    "CCAB": { name: "Selini", img: "img/selini-fit.png" },
    "CDDA": { name: "Selini", img: "img/selini-fit.png" },
    "CAAD": { name: "Selini", img: "img/selini-fit.png" },
    "CCAC": { name: "Selini", img: "img/selini-fit.png" },
    "CDDB": { name: "Selini", img: "img/selini-fit.png" },
    "CABA": { name: "Selini", img: "img/selini-fit.png" },
    "CCAD": { name: "Selini", img: "img/selini-fit.png" },
    "CDDC": { name: "Selini", img: "img/selini-fit.png" },
    "CABC": { name: "Selini", img: "img/selini-fit.png" },
    "CCBA": { name: "Selini", img: "img/selini-fit.png" },
    "DCAC": { name: "Selini", img: "img/selini-fit.png" },
    "CABD": { name: "Selini", img: "img/selini-fit.png" },
    "CCBB": { name: "Selini", img: "img/selini-fit.png" },
    "DCBC": { name: "Selini", img: "img/selini-fit.png" },
    "CACA": { name: "Selini", img: "img/selini-fit.png" },
    "CCBC": { name: "Selini", img: "img/selini-fit.png" },
    "DCCC": { name: "Selini", img: "img/selini-fit.png" },
    "CACB": { name: "Selini", img: "img/selini-fit.png" },
    "CCBD": { name: "Selini", img: "img/selini-fit.png" },
    "DCDC": { name: "Selini", img: "img/selini-fit.png" },
    "CACC": { name: "Selini", img: "img/selini-fit.png" },
    "CCCA": { name: "Selini", img: "img/selini-fit.png" },
    "CACD": { name: "Selini", img: "img/selini-fit.png" },
    "CCCB": { name: "Selini", img: "img/selini-fit.png" },
    "CADC": { name: "Selini", img: "img/selini-fit.png" },
    "CCCC": { name: "Selini", img: "img/selini-fit.png" },
    "CBAB": { name: "Selini", img: "img/selini-fit.png" },
    "CCCD": { name: "Selini", img: "img/selini-fit.png" },
    "CBAC": { name: "Selini", img: "img/selini-fit.png" },
    "CCDA": { name: "Selini", img: "img/selini-fit.png" },
    "CBAD": { name: "Selini", img: "img/selini-fit.png" },
    "CCDB": { name: "Selini", img: "img/selini-fit.png" },
    "CBBA": { name: "Selini", img: "img/selini-fit.png" },
    "CCDC": { name: "Selini", img: "img/selini-fit.png" },
    "CBBC": { name: "Selini", img: "img/selini-fit.png" },
    "CCDD": { name: "Selini", img: "img/selini-fit.png" },
    "AAAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABDC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADCC": { name: "Bniini", img: "img/bniini-fit.png" },
    "AAAB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABDD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADDA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AAAC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADDB": { name: "Bniini", img: "img/bniini-fit.png" },
    "AAAD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACAB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADDC": { name: "Bniini", img: "img/bniini-fit.png" },
    "AABA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACAC": { name: "Bniini", img: "img/bniini-fit.png" },
    "BAAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AABC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACAD": { name: "Bniini", img: "img/bniini-fit.png" },
    "BBAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AABD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACBA": { name: "Bniini", img: "img/bniini-fit.png" },
    "BCAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AACA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACBD": { name: "Bniini", img: "img/bniini-fit.png" },
    "BDAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AACB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACCA": { name: "Bniini", img: "img/bniini-fit.png" },
    "CAAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AACC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACCB": { name: "Bniini", img: "img/bniini-fit.png" },
    "CBAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AACD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACCD": { name: "Bniini", img: "img/bniini-fit.png" },
    "CDAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "AADA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACDA": { name: "Bniini", img: "img/bniini-fit.png" },
    "DAAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACDB": { name: "Bniini", img: "img/bniini-fit.png" },
    "DBAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABAB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ACDD": { name: "Bniini", img: "img/bniini-fit.png" },
    "DCAA": { name: "Bniini", img: "img/bniini-fit.png" }, 
    "ABAC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADAA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABAD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADAB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABBA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADAC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABBC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADAD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABBD": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADBA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABCA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADBC": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABDA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADCA": { name: "Bniini", img: "img/bniini-fit.png" },
    "ABDB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADCB": { name: "Bniini", img: "img/bniini-fit.png" },
    "ADBD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBAD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDBA" : { name: "Conini", img: "img/conini-fit.png" },
    "ADCD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBBA" : { name: "Conini", img: "img/conini-fit.png" },
    "DDBB" : { name: "Conini", img: "img/conini-fit.png" },
    "ADDD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBBC" : { name: "Conini", img: "img/conini-fit.png" },
    "DDBC" : { name: "Conini", img: "img/conini-fit.png" },
    "BDAD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBBD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDBD" : { name: "Conini", img: "img/conini-fit.png" },
    "BDCD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBCD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDCA" : { name: "Conini", img: "img/conini-fit.png" },
    "BDDD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBDA" : { name: "Conini", img: "img/conini-fit.png" },
    "DDCB" : { name: "Conini", img: "img/conini-fit.png" },
    "CDAD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBDB" : { name: "Conini", img: "img/conini-fit.png" },
    "DDCC" : { name: "Conini", img: "img/conini-fit.png" },
    "CBBD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBDC" : { name: "Conini", img: "img/conini-fit.png" },
    "DDCD" : { name: "Conini", img: "img/conini-fit.png" },
    "CDCD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBDD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDDA" : { name: "Conini", img: "img/conini-fit.png" },
    "CDDD" : { name: "Conini", img: "img/conini-fit.png" },
    "DCAB" : { name: "Conini", img: "img/conini-fit.png" },
    "DDDB" : { name: "Conini", img: "img/conini-fit.png" },
    "DAAB" : { name: "Conini", img: "img/conini-fit.png" },
    "DCAD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDDC" : { name: "Conini", img: "img/conini-fit.png" },
    "DABA" : { name: "Conini", img: "img/conini-fit.png" },
    "DCBA" : { name: "Conini", img: "img/conini-fit.png" },
    "DDDD" : { name: "Conini", img: "img/conini-fit.png" },
    "DABC" : { name: "Conini", img: "img/conini-fit.png" },
    "DCBD" : { name: "Conini", img: "img/conini-fit.png" },
    "DAAC" : { name: "Conini", img: "img/conini-fit.png" },
    "DCCA" : { name: "Conini", img: "img/conini-fit.png" },
    "DAAD" : { name: "Conini", img: "img/conini-fit.png" },
    "DCCB" : { name: "Conini", img: "img/conini-fit.png" },
    "DABA" : { name: "Conini", img: "img/conini-fit.png" },
    "DCCD" : { name: "Conini", img: "img/conini-fit.png" },
    "DABC" : { name: "Conini", img: "img/conini-fit.png" },
    "DCDA" : { name: "Conini", img: "img/conini-fit.png" },
    "DABD" : { name: "Conini", img: "img/conini-fit.png" },
    "DCDB" : { name: "Conini", img: "img/conini-fit.png" },
    "DACA" : { name: "Conini", img: "img/conini-fit.png" },
    "DCDD" : { name: "Conini", img: "img/conini-fit.png" },
    "DACB" : { name: "Conini", img: "img/conini-fit.png" },
    "DDAA" : { name: "Conini", img: "img/conini-fit.png" },
    "DACC" : { name: "Conini", img: "img/conini-fit.png" },
    "DDAB" : { name: "Conini", img: "img/conini-fit.png" },
    "DACD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDAC" : { name: "Conini", img: "img/conini-fit.png" },
    "DADD" : { name: "Conini", img: "img/conini-fit.png" },
    "DDAD" : { name: "Conini", img: "img/conini-fit.png" },
    "DBAB" : { name: "Conini", img: "img/conini-fit.png" },
    "DDAC" : { name: "Conini", img: "img/conini-fit.png" },
    "DBAC" : { name: "Conini", img: "img/conini-fit.png" },
    "DDAD" : { name: "Conini", img: "img/conini-fit.png" },  
    "AADB": { name: "Chonini", img: "img/chonini-fit.png" },
    "AADC": { name: "Chonini", img: "img/chonini-fit.png" },
    "AADD": { name: "Chonini", img: "img/chonini-fit.png" },
    "BADA": { name: "Chonini", img: "img/chonini-fit.png" },
    "BADC": { name: "Chonini", img: "img/chonini-fit.png" },
    "BADD": { name: "Chonini", img: "img/chonini-fit.png" },
    "CADA": { name: "Chonini", img: "img/chonini-fit.png" },
    "CADB": { name: "Chonini", img: "img/chonini-fit.png" },
    "CADD": { name: "Chonini", img: "img/chonini-fit.png" },
    "DADA": { name: "Chonini", img: "img/chonini-fit.png" },
    "DADB": { name: "Chonini", img: "img/chonini-fit.png" },
    "DADC": { name: "Chonini", img: "img/chonini-fit.png" }, 
    "ABCB": { name: "Jenini", img: "img/jenini-fit.png" },
    "ABCC": { name: "Jenini", img: "img/jenini-fit.png" },
    "ABCD": { name: "Jenini", img: "img/jenini-fit.png" },
    "BBCA": { name: "Jenini", img: "img/jenini-fit.png" },
    "BBCC": { name: "Jenini", img: "img/jenini-fit.png" },
    "BBCD": { name: "Jenini", img: "img/jenini-fit.png" },
    "CBCA": { name: "Jenini", img: "img/jenini-fit.png" },
    "CBCB": { name: "Jenini", img: "img/jenini-fit.png" },
    "CBCD": { name: "Jenini", img: "img/jenini-fit.png" },
    "DBCA": { name: "Jenini", img: "img/jenini-fit.png" },
    "DBCB": { name: "Jenini", img: "img/jenini-fit.png" },
    "DBCC": { name: "Jenini", img: "img/jenini-fit.png" }
};